export const PERFORMANCE_THRESHOLDS = {
  LOW_MEMORY: 2, // GB
  LOW_CORES: 4,
  HIGH_MEMORY: 8,
  HIGH_CORES: 8,
} as const;

export const PERFORMANCE_DEFAULT = {
  MEMORY: 4,
  HARDWARE_CONCURRENCY: 2,
}